### ISSUE TITLE
Vue dependency have to be installed when we want to use React.

### ISSUE THREAD

**Issue by lhapaipai** [lhapaipai/vite-plugin-symfony#35] opened 2023-12-04 09:42 UTC
### vite-plugin-symfony version

6.3.0

### vite-bundle version

6.3.0

### Description

```
$ npm run dev

> dev
> vite

Forced re-optimization of dependencies

  VITE v5.0.4  ready in 303 ms

  ➜  Local:   http://localhost:5173/build/
  ➜  Network: use --host to expose
  ➜  Vite ⚡️Symfony
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "vue"

    node_modules/vite-plugin-symfony/dist/stimulus/helpers/index.mjs:76:37:
      76 │ import { defineAsyncComponent } from "vue";
         ╵                                      ~~~~~

  You can mark the path "vue" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

```

### How to reproduce

```js
// bootstrap.js

import { startStimulusApp, registerReactControllerComponents, registerControllers } from "vite-plugin-symfony/stimulus/helpers" 
registerReactControllerComponents(import.meta.glob('./react/controllers/**/*.[jt]s(x)\?')); 

const app = startStimulusApp();
registerControllers(app, import.meta.glob('./controllers/*_(lazy)\?controller.[jt]s(x)\?'))
```
```jsx
// ./assets/react/controllers/ReactAdmin.jsx
import { HydraAdmin } from "@api-platform/admin";
import React from 'react';
export default (props) => (
  <HydraAdmin entrypoint={props.entrypoint} />
);
```

### Possible Solution

make svelte/react/vue helpers independants each others ?

**Comment by dotdevpro** [comment] 2023-12-15 03:35
+1, i think the problem is in output build, index.mjs in helpers/ exports all the modules but there should be a way to import them separatly for react/vue/svelte/stimulus because when we try import them from helpers/index.mjs which will require to import vue from vue helpers even there is no vue usage in project. Something like:

```ts
import {
  registerReactControllerComponents
} from 'vite-plugin-symfony/stimulus/helpers/react';
import {
   startStimulusApp,
   registerControllers,
} from 'vite-plugin-symfony/stimulus/helpers/stimulus';
```
Currently we can import only whole helpers module:
```ts
import {
  startStimulusApp,
  registerControllers,
  registerReactControllerComponents
} from 'vite-plugin-symfony/stimulus/helpers';
```
 which causes this error for projects without vue installed. This can be fixed with ```npm i vue``` but i dont think this is right way for react based projects. Actually in the source they are already separate, the problem only with "dist/" build folder.

**Closed** 2023-12-30 17:31 UTC
Labels: bug
